name: Scraping

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 21 * * *'

env:
  BASE_BRANCH_NAME: faeture/auto_scraping

jobs:
  add-new-file:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          cd $GITHUB_WORKSPACE
          git fetch
      - name: Checkout
        run: |
          git fetch
          git checkout -b $BASE_BRANCH_NAME
          git pull
      - name: Pip install
        run: pip install -r requirements.txt
      - name: Add new file
        run: python scraping.py
      - name: Check branch
        run: git branch
      - name: Commit
        run: |
          git add .
          git commit -m 'Generated automatically'
          git push origin $BASE_BRANCH_NAME
      - name: Teardown when the workflow failed
        if: failure() && steps.build_step.outcome == 'failure'
        run: |
          git stash -u
